---
title: "linear_models"
author: "Sophia Chkonia"
date: "2022-11-10"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)


```



```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```


## fit first model 

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)


fit

summary(fit)

summary(fit)$coef

fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borouogh:")
  ) %>% 
  select(
    term, estimate, p.value
  ) %>% 
  knitr::kable(digits = 2)

```

Let's change reference category. 

```{r}
fit =
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough)
  ) %>% 
  lm(price ~ stars + borough, data = .)

fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borouogh:")
  ) %>% 
  select(
    term, estimate, p.value
  ) %>% 
  knitr::kable(digits = 2)


fit %>% 
  broom::glance() %>% 
  select(AIC)
```





